name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'src/**.js'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Build
      run: |
        npm install
        npx webpack
    
    
    - name: Commit compiled source
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add "dist/*"
        git commit -m "Webpack Compile: ${{ github.event.head_commit.message }} " -m "Commit:  ${{ github.event.head_commit.id }}"   || echo "No Change"

    - name: Push changes
      env:
        TOKEN: ${{secrets.ACCESS_TOKEN}}
        REF: github.com/${{github.repository}}
      run: git push --force --quiet "https://${TOKEN}@${REF}" 
  
  copy-to-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: copy compiled source
      run: |
        cp dist/main.js /tmp/main.js

    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    
    - run: mkdir -p dist
    - run: cp /tmp/main.js dist/main.js

    - name: Commit 
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add "dist/*"
        git commit -m "Webpack Compile data: ${{ github.event.head_commit.message }}" -m "Commit: ${{ github.event.head_commit.id }}" || echo "No Change"
        
    - name: Push changes
      env:
        TOKEN: ${{secrets.ACCESS_TOKEN}}
        REF: github.com/${{github.repository}}
      run: git push --force --quiet "https://${TOKEN}@${REF}" 




