name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Build
      run: |
        npm install
        npx webpack
    
    
    - name: Commit compiled source
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add ""
        git commit -m "Compiled by webpack" -m "Commit:  ${{ github.event.head_commit.id }}" -m "Message: ${{ github.event.head_commit.message }} "  || echo "No Change"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
